[workspace]
authors = ["Jay Shenoy <jay@jayshenoy.com>"]
channels = ["conda-forge"]
name = "clip-drug-internal"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.5,<3.15"
pandas = ">=3.0.3,<4"
numpy = ">=2.4.6,<3"
scipy = ">=1.17.1,<2"
matplotlib = ">=3.10.9,<4"
seaborn = ">=0.13.2,<0.14"
networkx = ">=3.6.1,<4"
python-louvain = ">=0.16,<0.17"
